### PR TITLE
added magicbroccoli.de

### PR DESCRIPTION
**Pull request by mightyBroccoli**
magicbroccoli.de

### CODE REVIEW

**Comment by ge0rg** [comment]
Isn't https://magicbroccoli.de/xmpp/ a more appropriate link for your xmpp service?

**Comment by mightyBroccoli** [comment]
Yeah possible that might be way more accurate. I will change that.

**Comment by mightyBroccoli** [comment]
I now used the markdown syntax to use the /xmpp Link but display just the base Domain to fit the schema.

**Comment by ge0rg** [comment]
I haven't used markdown syntax anywhere else, e.g. for yax.im, so I'm keeping this simple for consistency. Merged, squashed and rewritten.

**Pull request closed without merging**
