### PR TITLE
Signed manifesto

### PR DESCRIPTION
**Pull request by bluszcz**

### CODE REVIEW

**Comment by ge0rg** [comment]
Your server doesn't implement XEP-0157 abuse address yet. Please fix that.

**Comment by bluszcz** [comment]
Could you please check now?

**Comment by ge0rg** [comment]
> Server-to-server connection failed: Connecting failed: connection refused

looks like an uptime problem?

**Comment by bluszcz** [comment]
It should work now. I hope it (manifesto) will work out - I have just received bunch spam contact request, again :(

**Comment by ge0rg** [comment]
> jabberpl.org can't be reached via XMPP

> Could not reach jabberpl.org: remote-server-not-found

This looks like the server is up but not configured for that domain?

**Comment by bluszcz** [comment]
How do you check? I made basic checks yesterday and s2s was working. Could you send me snippet please to test against?

**Comment by ge0rg** [comment]
There is a bot in our MUC that provides contact info; but currently even running a `/version jabberpl.org` from my client leads to errors.

Server log:

```
Feb 15 10:21:28 s2sout17cc1170  info    Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
Feb 15 10:21:28 s2sout17cc1170  debug   certificate chain validation result: valid
Feb 15 10:21:28 x509    debug   Cert dNSName jabberpl.org matched hostname
Feb 15 10:21:28 s2sout17cc1170  debug   certificate identity validation result: valid
Feb 15 10:21:28 s2sout17cc1170  debug   Received[s2sout_unauthed]: <features xmlns='http://etherx.jabber.org/streams'>
Feb 15 10:21:28 yax.im:tls      debug   Received features element
Feb 15 10:21:28 yax.im:saslauth debug   Initiating SASL EXTERNAL with jabberpl.org
Feb 15 10:21:28 s2sout17cc1170  debug   sending: <auth mechanism='EXTERNAL' xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Feb 15 10:21:28 s2sout17cc1170  debug   Received[s2sout_unauthed]: <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
Feb 15 10:21:28 yax.im:saslauth info    SASL EXTERNAL with jabberpl.org failed: not-authorized: unable to get local issuer certificate
Feb 15 10:21:28 s2sout17cc1170  debug   sending: </stream:stream>
```

Looks like your certificate isn't set up properly. You can check via https://xmpp.net .

**Comment by bluszcz** [comment]
Last check was fine: https://xmpp.net/result.php?domain=jabberpl.org&type=server currently checks don't work - server says is busy.

**Comment by horazont** [comment]
@bluszcz The busyness is hopefully fixed for good now. I re-ran the check and it *seems* to me that it should be okay.

**Comment by bluszcz** [comment]
I will investigate on evening more.

**Comment by bluszcz** [comment]
@ge0rg what about check from your endpoint?

**Comment by bluszcz** [comment]
So, actually it is quite weird. 

I made a test accounts on two other servers and was able to send messages both directions. However, now observatory says "Error: Connection failed." Not sure, but investigating now.

**Comment by ge0rg** [comment]
Alright, it's working now!

> Contact addresses for jabberpl.org are mailto:a****@jabberpl.org (admin)
> xmpp:b******@jabberpl.org (admin) mailto:a****@jabberpl.org (abuse)

**Pull request merged**
