### PR TITLE
Add jabber.no to the manifest

### PR DESCRIPTION
**Pull request by corvy**
Please add jabber.no to the manifest. Thanks

### CODE REVIEW

**Comment by horazont** [comment]
* [x] XEP-0157 abuse contact address present

**Comment by ge0rg** [comment]
The server link redirects to https://www.jabber.no/en/ which is a 404. Could you please kindly fix that as well?

**Comment by corvy** [comment]
Ah, due to english language I do not get that error. Yes I will fix it.

**Comment by Neustradamus** [comment]
@corvy: Any news about changes that I have sent you? In the same time, your cert is now expired.

**Comment by Neustradamus** [comment]
@horazont: Can you confirm it?

**Comment by corvy** [comment]
I have fixed the cert and added a cronjob to renew. Hopefully it will no expire again. I think the redirect should be working now, please test and tell me if it does not work. Thanks!

**Comment by ge0rg** [comment]
Merged in 241fe4ea79a2e728e7a2755008d2fd1bcb1d7826

**Pull request closed without merging**
