### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Mass protest of users to manifest points on registration by number and single block list. (Yes, we understand that these are not mandatory points, but users protest against mentioning, not compliance)

404.city will continue to fight spam and block spammers' accounts without signing in manifest

### CODE REVIEW

**Comment by licaon-kter** [comment]
How much is "Mass protest" exactly?

**Comment by ghost** [comment]
No one supports the manifest.  So the manifest contains errors.  Errors consist in blocking the servers of victims of spammers.  spammers create accounts manually on multiple servers.  Automatic measures are ineffective against manually creating accounts.  it is necessary to strike at the spammers accomplices.  spammers' accomplices are servers that allow you to order spam mailings and refuse to block feedback forms for buying spam mailings.
Sustainable financing of spam mailings is a more serious problem than abandoned servers.

**Comment by ghost** [comment]
in fact, a spam manifest is anti-advertising for signatory parties.  because the manifest does not have the approval of most XMPP users. people are afraid that they will block innocent servers not listed in the manifest (this was one of the reasons and my consent to sign)

Participants who do not sign the manifesto, but abide by the manifesto have an advantage. They do not stand next to the words spamlist and phone verification.

My opinion: in the manifest it is necessary either to include all servers de-facto supporting the fight against spam, or not to include anyone.

forced inclusion in the manifest that respects the manifest (blocking spammers and has captcha) will make the XMPP community understand the purpose of the manifest.

We must decide the real things, and not engage in politics. I would prefer a complete de-listing all participants or add all, but I cannot do this.

**Comment by licaon-kter** [comment]
...or do not respond to my question, that works too.

**Comment by ghost** [comment]
Mass protest is all i asked

**Comment by mdosch** [comment]
Can you give a number?

**Comment by ghost** [comment]
I got 10 negative reviews out of 10. that's enough.

**Pull request merged**
